<?php

namespace Database\Seeders;

use App\Enums\PersonType;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CustomerSeeder extends Seeder
{
    public function run(): void
    {
        $now = now();

        DB::table('customers')->insertOrIgnore([
            [
                'name' => 'João da Silva',
                'document' => '52998224725',
                'email' => 'joao.silva@email.com',
                'type' => PersonType::INDIVIDUAL->value,
                'birth_date' => '1990-08-15',
                'phone' => '48999991234',
                'secondary_phone' => '48988884321',
                'zip_code' => '88701000',
                'street' => 'Rua Laguna',
                'number' => '123',
                'complement' => null,
                'district' => 'Centro',
                'city' => 'Tubarão',
                'state' => 'SC',
                'notes' => 'Cliente cadastrado via seed.',
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Maria Oliveira',
                'document' => '39053344705',
                'email' => 'maria.oliveira@email.com',
                'type' => PersonType::INDIVIDUAL->value,
                'birth_date' => '1988-04-22',
                'phone' => '11998881122',
                'secondary_phone' => null,
                'zip_code' => '01310100',
                'street' => 'Avenida Paulista',
                'number' => null,
                'complement' => 'Apartamento 1201',
                'district' => 'Bela Vista',
                'city' => 'São Paulo',
                'state' => 'SP',
                'notes' => null,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Pedro Souza',
                'document' => '11144477735',
                'email' => 'pedro.souza@email.com',
                'type' => PersonType::INDIVIDUAL->value,
                'birth_date' => null,
                'phone' => '48999990000',
                'secondary_phone' => null,
                'zip_code' => '88700000',
                'street' => 'Rua XV de Novembro',
                'number' => '10',
                'complement' => null,
                'district' => 'Centro',
                'city' => 'Tubarão',
                'state' => 'SC',
                'notes' => null,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Ana Paula Martins',
                'document' => '15350946056',
                'email' => 'ana.martins@email.com',
                'type' => PersonType::INDIVIDUAL->value,
                'birth_date' => '1995-11-03',
                'phone' => '47991234567',
                'secondary_phone' => '47987654321',
                'zip_code' => '89010000',
                'street' => 'Rua das Palmeiras',
                'number' => '88',
                'complement' => null,
                'district' => 'Centro',
                'city' => 'Blumenau',
                'state' => 'SC',
                'notes' => null,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Carlos Henrique Lima',
                'document' => '87418896069',
                'email' => 'carlos.lima@email.com',
                'type' => PersonType::INDIVIDUAL->value,
                'birth_date' => '1982-02-10',
                'phone' => '41999887766',
                'secondary_phone' => null,
                'zip_code' => '80010000',
                'street' => 'Rua Marechal Deodoro',
                'number' => null,
                'complement' => 'Casa fundos',
                'district' => 'Centro',
                'city' => 'Curitiba',
                'state' => 'PR',
                'notes' => 'Prefere contato por WhatsApp.',
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Fernanda Costa',
                'document' => '03350352057',
                'email' => 'fernanda.costa@email.com',
                'type' => PersonType::INDIVIDUAL->value,
                'birth_date' => null,
                'phone' => '48987651234',
                'secondary_phone' => null,
                'zip_code' => '88801000',
                'street' => 'Avenida Centenário',
                'number' => '200',
                'complement' => null,
                'district' => 'Próspera',
                'city' => 'Criciúma',
                'state' => 'SC',
                'notes' => null,
                'is_active' => false,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Roberto Almeida',
                'document' => '31372030077',
                'email' => 'roberto.almeida@email.com',
                'type' => PersonType::INDIVIDUAL->value,
                'birth_date' => '1979-07-19',
                'phone' => '51991239876',
                'secondary_phone' => '5133332222',
                'zip_code' => '90010000',
                'street' => 'Rua dos Andradas',
                'number' => '501',
                'complement' => null,
                'district' => 'Centro Histórico',
                'city' => 'Porto Alegre',
                'state' => 'RS',
                'notes' => null,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Juliana Pereira',
                'document' => '72890064026',
                'email' => 'juliana.pereira@email.com',
                'type' => PersonType::INDIVIDUAL->value,
                'birth_date' => '1992-12-01',
                'phone' => '48999112233',
                'secondary_phone' => null,
                'zip_code' => '88704000',
                'street' => 'Rua Padre Geraldo Spettmann',
                'number' => '45',
                'complement' => null,
                'district' => 'Humaitá',
                'city' => 'Tubarão',
                'state' => 'SC',
                'notes' => null,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Rafael Mendes',
                'document' => '24750547000',
                'email' => 'rafael.mendes@email.com',
                'type' => PersonType::INDIVIDUAL->value,
                'birth_date' => null,
                'phone' => '21988776655',
                'secondary_phone' => null,
                'zip_code' => '20040002',
                'street' => 'Avenida Rio Branco',
                'number' => null,
                'complement' => 'Sala 304',
                'district' => 'Centro',
                'city' => 'Rio de Janeiro',
                'state' => 'RJ',
                'notes' => null,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Patrícia Rocha',
                'document' => '97070885083',
                'email' => 'patricia.rocha@email.com',
                'type' => PersonType::INDIVIDUAL->value,
                'birth_date' => '1986-05-27',
                'phone' => '31999881234',
                'secondary_phone' => '3133334455',
                'zip_code' => '30140071',
                'street' => 'Rua da Bahia',
                'number' => '1200',
                'complement' => null,
                'district' => 'Lourdes',
                'city' => 'Belo Horizonte',
                'state' => 'MG',
                'notes' => 'Cliente recorrente.',
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Oficina Mecânica Turbo LTDA',
                'document' => '11222333000181',
                'email' => 'contato@turbo.com.br',
                'type' => PersonType::COMPANY->value,
                'birth_date' => null,
                'phone' => '4833334444',
                'secondary_phone' => null,
                'zip_code' => '88702500',
                'street' => 'Rua dos Mecânicos',
                'number' => '450',
                'complement' => null,
                'district' => 'Oficinas',
                'city' => 'Tubarão',
                'state' => 'SC',
                'notes' => 'Cliente PJ com faturamento mensal.',
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Auto Peças Sul Comércio Ltda',
                'document' => '12345678000195',
                'email' => 'financeiro@autopecassul.com.br',
                'type' => PersonType::COMPANY->value,
                'birth_date' => null,
                'phone' => '5133339876',
                'secondary_phone' => '51999991111',
                'zip_code' => '90010000',
                'street' => 'Rua dos Andradas',
                'number' => null,
                'complement' => 'Sala 501',
                'district' => 'Centro Histórico',
                'city' => 'Porto Alegre',
                'state' => 'RS',
                'notes' => null,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Centro Automotivo União Ltda',
                'document' => '04252011000110',
                'email' => 'contato@uniauto.com.br',
                'type' => PersonType::COMPANY->value,
                'birth_date' => null,
                'phone' => '4133221100',
                'secondary_phone' => null,
                'zip_code' => '80230010',
                'street' => 'Avenida Sete de Setembro',
                'number' => '1710',
                'complement' => null,
                'district' => 'Rebouças',
                'city' => 'Curitiba',
                'state' => 'PR',
                'notes' => null,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Garagem Premium Serviços Automotivos',
                'document' => '18781203000128',
                'email' => 'atendimento@garagempremium.com.br',
                'type' => PersonType::COMPANY->value,
                'birth_date' => null,
                'phone' => '4833332211',
                'secondary_phone' => '48999998888',
                'zip_code' => '88010000',
                'street' => 'Rua Felipe Schmidt',
                'number' => '300',
                'complement' => null,
                'district' => 'Centro',
                'city' => 'Florianópolis',
                'state' => 'SC',
                'notes' => 'Empresa parceira.',
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Mecânica Avenida Ltda',
                'document' => '30735328000117',
                'email' => 'mecanicaavenida@email.com',
                'type' => PersonType::COMPANY->value,
                'birth_date' => null,
                'phone' => '1133334455',
                'secondary_phone' => null,
                'zip_code' => '01001000',
                'street' => 'Praça da Sé',
                'number' => '55',
                'complement' => null,
                'district' => 'Sé',
                'city' => 'São Paulo',
                'state' => 'SP',
                'notes' => null,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Auto Center Brasil Ltda',
                'document' => '33583931000119',
                'email' => 'contato@autocenterbrasil.com.br',
                'type' => PersonType::COMPANY->value,
                'birth_date' => null,
                'phone' => '2132227788',
                'secondary_phone' => null,
                'zip_code' => '20010020',
                'street' => 'Rua Primeiro de Março',
                'number' => null,
                'complement' => 'Loja 02',
                'district' => 'Centro',
                'city' => 'Rio de Janeiro',
                'state' => 'RJ',
                'notes' => null,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Peças e Motores Catarinense LTDA',
                'document' => '47752532000149',
                'email' => 'vendas@pmcatarinense.com.br',
                'type' => PersonType::COMPANY->value,
                'birth_date' => null,
                'phone' => '4733338899',
                'secondary_phone' => '47999990011',
                'zip_code' => '89201000',
                'street' => 'Rua do Príncipe',
                'number' => '780',
                'complement' => null,
                'district' => 'Centro',
                'city' => 'Joinville',
                'state' => 'SC',
                'notes' => 'Fornecedor e cliente.',
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Rodasul Comércio de Pneus Ltda',
                'document' => '59934755000106',
                'email' => 'financeiro@rodasul.com.br',
                'type' => PersonType::COMPANY->value,
                'birth_date' => null,
                'phone' => '4832109988',
                'secondary_phone' => null,
                'zip_code' => '88705500',
                'street' => 'Avenida Patrício Lima',
                'number' => '950',
                'complement' => null,
                'district' => 'Humaitá',
                'city' => 'Tubarão',
                'state' => 'SC',
                'notes' => null,
                'is_active' => false,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Sul Diesel Manutenção Ltda',
                'document' => '75168469000133',
                'email' => 'contato@suldiesel.com.br',
                'type' => PersonType::COMPANY->value,
                'birth_date' => null,
                'phone' => '5132104455',
                'secondary_phone' => null,
                'zip_code' => '90230060',
                'street' => 'Avenida Farrapos',
                'number' => '2500',
                'complement' => null,
                'district' => 'São Geraldo',
                'city' => 'Porto Alegre',
                'state' => 'RS',
                'notes' => 'Atende frota diesel.',
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Litoral Auto Serviços Ltda',
                'document' => '86874456000104',
                'email' => 'litoralauto@email.com',
                'type' => PersonType::COMPANY->value,
                'birth_date' => null,
                'phone' => '4733445566',
                'secondary_phone' => '47988887777',
                'zip_code' => '88330000',
                'street' => 'Avenida Brasil',
                'number' => null,
                'complement' => 'Galpão 04',
                'district' => 'Centro',
                'city' => 'Balneário Camboriú',
                'state' => 'SC',
                'notes' => null,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ]);
    }
}
